import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import {icon as sourceIcon,shapes} from '../mediterranean/icons.mjs';
import {integrateMaterialRecognition} from '../material-recognition/component.mjs';
const dir=path.dirname(fileURLToPath(import.meta.url)),demo=path.dirname(dir),root=path.dirname(demo);
const require=createRequire(path.join(process.env.TEMP,'ecoclean-demo-qa/package.json'));
const {JSDOM}=require('jsdom');
export function createStudioTransformer(referenceHTML){
const assets=JSON.parse(fs.readFileSync(path.join(dir,'asset-manifest.json'),'utf8'));
const reference=new JSDOM(referenceHTML);
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cityNames={badacsony:'Badacsony',balatonalmadi:'Balatonalmádi',balatonboglar:'Balatonboglár',balatonfoldvar:'Balatonföldvár',balatonfured:'Balatonfüred',balatonfuzfo:'Balatonfűzfő',balatonkenese:'Balatonkenese',balatonlelle:'Balatonlelle',balatonszemes:'Balatonszemes',fonyod:'Fonyód',gyor:'Győr',heviz:'Hévíz',keszthely:'Keszthely',komarom:'Komárom',mosonmagyarovar:'Mosonmagyaróvár',papa:'Pápa',revfulop:'Révfülöp',siofok:'Siófok',sopron:'Sopron',szombathely:'Szombathely',tapolca:'Tapolca',tata:'Tata',tatabanya:'Tatabánya',tihany:'Tihany',veszprem:'Veszprém',zamardi:'Zamárdi'};
const files={living:'l-alaku-kanape-vilagos-nappali.webp',sofa:'szofa-lenkarpit-varosi-nappali.webp',armchair:'fotel-bukle-olvasosarok.webp',dining:'karpitozott-ebedloszek-tolgy-etkezo.webp',office:'karpitozott-irodai-szek-dolgozoszoba.webp',bedroom:'matrac-karpitozott-agy-vilagos-haloszoba.webp',heritage:'magyar-nappali-1980-as-evek-berendezes.webp',soil:'kanape-fejtamla-karfa-uleselo-szennyezodes.webp','mites-sofa':'poratka-petek-hamsejtek-kanape-szovet.webp','mites-mattress':'poratka-petek-matrac-szalak-mikrovilag.webp'};
const alts={living:'Világos L alakú szövetkanapé tölgyparkettás, gondosan berendezett nappaliban',sofa:'Kékesszürke lenhatású szófa travertin asztallal egy kortárs nappaliban',armchair:'Világos bukléfotel tölgy polcokkal kialakított olvasósarokban',dining:'Kárpitozott étkezőszékek ovális tölgy étkezőasztal körül',office:'Világos kárpitozott irodai szék egy letisztult otthoni dolgozószobában',bedroom:'Világos steppelt matrac kárpitozott ágyon, nyugodt hálószobai enteriőrben',heritage:'Az 1980-as évek magyar nappalija szekrénysorral, mintás kanapéval és csipkefüggönnyel',soil:'Sötétebb lerakódás a világos kanapé fejtámláján, karfáján és ülőlapjának elülső szélén','mites-sofa':'Poratkák, peték és hámsejtek a kanapé szövetszálai között, nagyított és nem méretarányos szemléltetés','mites-mattress':'Poratkák, peték és hámsejtek a matrac rostjai között, nagyított és nem méretarányos szemléltetés'};
const asset=id=>{const a=assets.find(a=>a.file===files[id]);if(!a)throw Error('Missing asset '+id);return a;};
const image=(id,cls='')=>{const a=asset(id);return `<img class="${cls}" src="studio/assets/${a.file}" width="${a.width}" height="${a.height}" loading="lazy" decoding="async" alt="${esc(alts[id])} – generált illusztráció" data-generated-interior="true">`;};
const icon=(name='leaf')=>`<span class="studio-icon studio-icon-${name}" aria-hidden="true"></span>`;
const iconNames=['home','sofa','armchair','bed','leaf','shield','drop','wind','mail','phone','pin','calendar'];
const iconSignatures=new Map(Object.keys(shapes).map(name=>{const holder=reference.window.document.createElement('div');holder.innerHTML=sourceIcon(name);return [holder.firstChild.innerHTML,name];}));
const iconFallbacks={dining:'armchair',office:'armchair',layers:'sofa',sun:'wind',time:'calendar',check:'shield',star:'shield',textile:'leaf',microscope:'shield',sparkle:'leaf',book:'leaf'};
const normalized=s=>s.replace(/[\p{Extended_Pictographic}\uFE0F\u200D\u2605\u2606]/gu,'').replace(/\s+/g,' ').trim();
function render(bytes,target){
 const dom=new JSDOM(bytes.toString()),d=dom.window.document,city=cityNames[target.city],mattress=target.service==='matractisztitas';
 const originalText=[...d.querySelectorAll('h1,h2,h3,p,.pricing-item-name,.pricing-price')].map(e=>normalized(e.textContent)).filter(Boolean);
 const originalImages=[...d.querySelectorAll('img[src]:not([data-generated-interior])')].map(e=>e.getAttribute('src'));
 const originalLinks=[...d.querySelectorAll('nav a[href],footer a[href]')].map(e=>e.getAttribute('href'));
 d.body.classList.add('eco-studio');
 for(const a of d.querySelectorAll('a[href]'))if(['aszf.html','adatvedelem.html','impresszum.html'].includes(a.getAttribute('href')))a.remove();
 const style=d.createElement('link');style.rel='stylesheet';style.href='studio/design.css';d.head.append(style);
 const fonts=d.createElement('link');fonts.rel='stylesheet';fonts.href='https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400;1,500&display=swap';d.head.append(fonts);
 // Replace decorative emoji everywhere, while retaining the original words and links.
 const walker=d.createTreeWalker(d.body,dom.window.NodeFilter.SHOW_TEXT);let n;const nodes=[];
 while(n=walker.nextNode())if(!n.parentElement.closest('script,style'))nodes.push(n);
 for(const node of nodes){if(!/[\p{Extended_Pictographic}\uFE0F\u200D\u2605\u2606]/u.test(node.textContent))continue;const text=node.textContent,name=/foglal/i.test(text)?'calendar':/telefon|hív|☎|📞/i.test(text)?'phone':/kiszáll|terület|🚚|📍/i.test(text)?'pin':/atka|garancia|véd/i.test(text)?'shield':'leaf';const span=d.createElement('span');span.className='studio-icon studio-icon-'+name;span.setAttribute('aria-hidden','true');node.before(span);node.textContent=text.replace(/[\p{Extended_Pictographic}\uFE0F\u200D\u2605\u2606]/gu,'');}
 const hero=d.querySelector('.subpage-hero'),pricing=d.querySelector('.pricing'),footer=d.querySelector('footer');if(!hero||!pricing||!footer)throw Error('Page contract differs '+target.file);
 const generated=[...d.querySelectorAll('img[data-generated-interior]')];
 for(const heading of d.querySelectorAll('h1,h2,h3')){const w=d.createTreeWalker(heading,dom.window.NodeFilter.SHOW_TEXT),list=[];let text;while(text=w.nextNode())if(text.textContent.includes('/'))list.push(text);for(const text of list){const parts=text.textContent.split('/'),fragment=d.createDocumentFragment();parts.forEach((part,i)=>{if(i){fragment.append(d.createTextNode('/'),d.createElement('wbr'));}fragment.append(d.createTextNode(part));});text.replaceWith(fragment);}}
 // Keep compound names legible at narrow widths, without changing their visible copy.
 for(const block of d.querySelectorAll('h1,h2,h3,p,.section-title')){const w=d.createTreeWalker(block,dom.window.NodeFilter.SHOW_TEXT),list=[];let text;while(text=w.nextNode())if(/(?:Balaton|Moson|vendég|[ÜüÖö]dülő)(?=[a-záéíóöőúüű])/u.test(text.textContent))list.push(text);for(const text of list){const fragment=d.createDocumentFragment(),parts=text.textContent.split(/((?:Balaton|Moson|vendég|[ÜüÖö]dülő))(?=[a-záéíóöőúüű])/u);parts.forEach((part,i)=>{fragment.append(d.createTextNode(part));if(i%2)fragment.append(d.createElement('wbr'));});text.replaceWith(fragment);}}
 for(const table of d.querySelectorAll('.comparison-table')){const region=d.createElement('div');region.className='studio-table-scroll';region.tabIndex=0;region.setAttribute('role','region');region.setAttribute('aria-label','Összehasonlító táblázat; keskeny képernyőn oldalirányban görgethető');table.before(region);region.append(table);}
 generated.forEach(img=>{const src=img.getAttribute('src');let id=mattress?'bedroom':'living';for(const [part,key] of [['sofa-card','sofa'],['armchair','armchair'],['dining','dining'],['office','office'],['bedroom','bedroom'],['mattress','bedroom']])if(src.includes(part))id=key;const a=asset(id);img.src='studio/assets/'+a.file;img.alt=alts[id]+' – generált illusztráció';img.width=a.width;img.height=a.height;});
 hero.querySelector('.subpage-hero-cta')?.insertAdjacentHTML('afterbegin','<a class="btn btn-primary" href="#studio-kalkulator">Képes árkalkulátor '+icon('sofa')+'</a>');
 const jump=d.createElement('nav');jump.className='studio-chapters';jump.setAttribute('aria-label','Ugrás az oldal témáihoz');jump.innerHTML='<a href="#studio-szobak">Otthonod terei</a><a href="#studio-kalkulator">Árkalkulátor</a><a href="#a-hasznalat-nyomai">Miért sötétedik?</a><a href="#egeszseg-es-biztonsag">A szálak között</a><a href="#studio-anyagok">Anyagkalauz</a>';hero.after(jump);
 const copy=selector=>{
  const section=reference.window.document.querySelector(selector).cloneNode(true);
  section.querySelectorAll('img[src]').forEach(img=>{const key=Object.keys(files).find(k=>img.getAttribute('src').endsWith('/'+k+'.webp'));if(key){const a=asset(key);img.src='studio/assets/'+a.file;img.alt=alts[key]+' – generált illusztráció';img.width=a.width;img.height=a.height;}});
  section.querySelectorAll('[data-zoom]').forEach(el=>{const key=el.dataset.zoom.includes('mattress')?'mites-mattress':'mites-sofa';el.dataset.zoom='studio/assets/'+files[key];});
  section.querySelectorAll('a[href="#arak"]').forEach(a=>a.href='#studio-kalkulator');
  section.querySelectorAll('svg').forEach(svg=>{const name=iconSignatures.get(svg.innerHTML)||'leaf',holder=d.createElement('span');holder.innerHTML=['arrow','plus'].includes(name)?`<span class="studio-symbol" aria-hidden="true">${name==='arrow'?'→':'+'}</span>`:icon(iconNames.includes(name)?name:iconFallbacks[name]||'leaf');svg.replaceWith(holder.firstChild);});
  return d.importNode(section,true);
 };
 const rooms=d.createElement('section');rooms.className='med-section studio-rooms';rooms.id='studio-szobak';
 rooms.innerHTML=`<div class="med-shell"><div class="med-section-top"><div class="med-heading"><span class="med-eyebrow">Egy otthon. Sok szeretett részlet.</span><h2>Melyik térnek adnál<br>új frissességet?</h2></div><p>A kanapé esti pihenése, a közös étkezések vagy a nyugodt alvás: válassz egy helyiséget, és nézd meg közelebbről a naponta használt kárpitozott felületeket.</p></div><div class="studio-room-tabs" role="tablist" aria-label="Otthonod helyiségei">${[['living','Nappali'],['dining','Étkező'],['office','Dolgozó'],['bedroom','Háló']].map(([id,label],i)=>`<button type="button" role="tab" id="room-tab-${id}" aria-controls="room-${id}" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-room-tab="${id}">${label}</button>`).join('')}</div>${[['living','A közös pillanatok helye.','A kanapé háttámlája, karfája és ülőfelülete eltérően kap terhelést. A tisztításnál a teljes bútort és az anyag kezelési előírását nézzük.','0'],['dining','A beszélgetések itt folytatódnak.','Az étkezőszék szövete a mindennapi étkezésekből is őrizhet nyomokat. A darabszám és a kárpitozott felületek mérete együtt fontos.','3'],['office','A munkanap kényelme.','Az irodai szék ülőlapja és háttámlája rendszeres használatban van. Az ápolt kárpit a rendezett munkakörnyezet része.','4'],['bedroom','Törődés a pihenés alapjával.','A matrac méretét és tisztítandó oldalait is válaszd ki. A huzat és a belső felépítés határozza meg a megfelelő eljárást.','5']].map(([id,title,body,focus],i)=>`<div class="studio-room-panel" role="tabpanel" id="room-${id}" aria-labelledby="room-tab-${id}"${i?' hidden':''}>${image(id)}<div><span class="med-eyebrow">${esc(city)} · Helyszíni tisztítás</span><h3>${title}</h3><p>${body}</p><a class="med-button" href="#studio-kalkulator" data-config-focus="${focus}">Kiválasztom a bútort ${icon('sofa')}</a></div></div>`).join('')}<p class="med-image-note">Saját generált enteriőr-illusztrációk; a valódi tisztítási eredményeket az eredeti referenciafotók mutatják.</p></div>`;
 jump.after(rooms);
 const furniture=copy('.med-furniture');rooms.after(furniture);
 const calc=d.createElement('section');calc.className='med-section med-price-section';calc.id='studio-kalkulator';calc.innerHTML=`<div class="med-shell"><div class="med-section-top"><div class="med-heading"><span class="med-eyebrow">${esc(city)} · Online megrendelés előkészítése</span><h2>Lásd a bútorokat.<br>Tervezd meg a tisztítást.</h2></div><p>Állítsd össze a tételeket, nézd meg a tájékoztató összeget, majd ellenőrizd és vidd át a választásodat a megrendelő űrlapra. Az időpontot és az elérhetőségeket ott adhatod meg.</p></div><div data-studio-configurator data-city="${target.city}" data-source-page="${target.file}" data-assets="studio/assets"><noscript>A képes kalkulátorhoz JavaScript szükséges. <a href="index.html#booking">Tovább a megrendelő űrlaphoz</a>.</noscript></div></div>`;pricing.after(calc);
 let last=calc;for(const selector of ['.med-history','.med-value','.med-soil','.med-mites','.med-care']){const section=copy(selector);last.after(section);last=section;if(selector==='.med-soil'){const img=section.querySelector('.med-hotspot-scene img'),a=asset('soil');img.src='studio/assets/'+a.file;img.alt=alts.soil+' – generált szemléltetés';img.width=a.width;img.height=a.height;}if(selector==='.med-mites'&&mattress){section.querySelectorAll('[data-mite-tab]').forEach(b=>{const active=b.dataset.miteTab==='mattress';b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;});section.querySelector('#mite-sofa').hidden=true;section.querySelector('#mite-mattress').hidden=false;}}
 calc.querySelector('[data-studio-configurator]').dataset.imageMap=JSON.stringify(Object.fromEntries(Object.entries({sofa:'sofa','l-sofa':'living','u-sofa':'living',armchair:'armchair',dining:'dining',office:'office',mattress:'bedroom'}).map(([key,id])=>[key,{...asset(id),alt:alts[id]+' – generált illusztráció'}])));
 const materials=d.createElement('section');materials.className='med-section studio-materials';materials.id='studio-anyagok';materials.innerHTML=`<div class="med-shell"><div class="med-section-top"><div class="med-heading"><span class="med-eyebrow">A szép felület mögött</span><h2>Minden szövet<br>más figyelmet kér.</h2></div><p>A látvány csak az első benyomás. A tisztítás előtt a címkét, a szálösszetételt, a színtartóságot és a bútor felépítését is figyelembe kell venni.</p></div><div class="studio-material-grid">${[['sofa','Szövött kárpit','A szálak között por és szennyeződés gyűlhet össze. Az anyaghoz illő, kíméletes portalanítás és az előzetes próba segít a megfelelő eljárás megválasztásában.'],['armchair','Buklé és karakteres textúrák','A hurkolt, domború felület másképp viselkedik dörzsölésre. A tisztítás módját a gyártói útmutatóhoz igazítjuk; az erős súrolást kerüld.'],['living','Világos, természetes hatású szövet','A világos szín hamarabb megmutatja a használat nyomait. A természetes megjelenésből nem következik a szálösszetétel vagy a moshatóság.'],['bedroom','Matrac és huzat','A cipzár önmagában nem jelenti, hogy a huzat mosható. A címke, a töltet, a ragasztások és a teljes száradás lehetősége is számít.']].map(([id,title,body],i)=>`<details class="studio-material"${i===0?' open':''}><summary>${image(id)}<span><b>0${i+1}</b>${title}</span>${icon('leaf')}</summary><p>${body}</p></details>`).join('')}</div><p class="med-fine-print">A képek anyaghangulatot szemléltetnek; nem helyettesítik az anyagvizsgálatot. <a href="https://www.kvadrat.dk/en/products/upholstery/1058-guest" target="_blank" rel="noopener noreferrer">Ápolási háttér: Kvadrat</a>.</p></div>`;last.after(materials);
 const process=copy('.med-process');process.querySelectorAll('h3')[1].textContent='Ellenőrzöd a megrendelést';process.querySelectorAll('article p')[1].textContent='Az összeállított tételeket a főoldali űrlapon ellenőrizheted. Ott választhatsz elérhető időpontot és adhatod meg az elérhetőségedet.';materials.after(process);
 const closing=copy('.med-closing');closing.querySelector('.med-closing-region').innerHTML=`<details class="studio-city-links"><summary>Kárpit- és matractisztítás másik településen</summary><nav class="med-city-nav" aria-label="Online foglalási területek">${Object.entries(cityNames).map(([slug,name])=>`<a href="${target.service}-${slug}.html"${slug===target.city?' aria-current="page"':''}>${name}</a>`).join('')}</nav></details>`;footer.before(closing);
 const careFaq=copy('.med-faq');careFaq.id='studio-kerdesek';careFaq.querySelector('h2').textContent='Az anyagról, az ápolásról, a lehetőségekről.';
 careFaq.querySelector('.med-faq-item:last-child p').textContent=`${city} és környékén a képes árkalkulátorral állíthatod össze a bútorokat és a tisztítás részleteit. A „Tovább a megrendelőhöz” gomb a főoldali űrlapra visz, ahol előbb átnézheted és átveheted a tételeket. Ezután választasz elérhető időpontot és adod meg az elérhetőségedet. Az árkalkuláció és a tételek átvétele önmagában még nem foglalás. Különleges anyagról, szállodai mennyiségről vagy egyedi igényről telefonon egyeztetünk.`;
 (d.querySelector('section.faq')||closing).before(careFaq);
 jump.insertAdjacentHTML('beforeend','<a href="#studio-kerdesek">Kérdések és válaszok</a>');
 const dialog=d.importNode(reference.window.document.querySelector('.med-image-dialog'),true);d.body.append(dialog);
 for(const src of ['studio/configurator.js','studio/interactions.js']){const script=d.createElement('script');script.src=src;script.defer=true;d.body.append(script);}
 const supplemental=d.createElement('script');supplemental.type='application/ld+json';supplemental.textContent=JSON.stringify({'@context':'https://schema.org','@type':'ImageObject',name:'Saját generált enteriőr-illusztráció',contentUrl:'https://ecocleantisztito.hu/studio/assets/'+files[mattress?'bedroom':'living'],description:alts[mattress?'bedroom':'living']});d.head.append(supplemental);
 if(!mattress)integrateMaterialRecognition(d);
 const currentText=normalized(d.body.textContent);const missingText=originalText.filter(t=>!currentText.includes(t)&&!t.includes('ÁSZF')&&!t.includes('Adatvédelem'));if(missingText.length)throw Error(target.file+' lost original copy: '+JSON.stringify(missingText.slice(0,4)));
 const ids=[...d.querySelectorAll('[id]')].map(e=>e.id);if(new Set(ids).size!==ids.length)throw Error('Duplicate ids '+target.file+': '+ids.filter((id,i)=>ids.indexOf(id)!==i));
 const output=dom.serialize();
 const evidence={...target,cityName:city,sourceSha256:sha(bytes),outputSha256:sha(output),originalTextBlocks:originalText.length,originalImages,originalLinks};
 dom.window.close();return {html:output,evidence};
 }
 return {render,close:()=>reference.window.close()};
}
