const asset='material-recognition/assets/fotel-bukle-olvasosarok.webp';
export function integrateMaterialRecognition(d,{home=false,next,assetUrl=asset}={}){
 d.getElementById('anyagfelismero')?.remove();
 const target=next||(home?'#booking':d.querySelector('[data-studio-configurator]')?'#studio-kalkulator':'#arak');
 const section=d.createElement('section');section.id='anyagfelismero';section.className='eco-material';section.setAttribute('aria-labelledby','material-title');
 section.innerHTML=`<div class="eco-material-shell"><div class="eco-material-intro"><span class="eco-material-eyebrow">Segítünk eligazodni a kárpitok között</span><h2 id="material-title">Nem vagy biztos benne,<br>milyen anyagból készült<br><em>a kárpit?</em></h2><p>Mutass egy közeli fotót, és megpróbáljuk megállapítani az anyag jellegét. Ha a kép alapján nem dönthető el, a kezelési címke vagy egy újabb részletfotó segíthet.</p><figure class="eco-material-editorial"><img src="${assetUrl}" width="1448" height="1086" alt="Világos bukléfotel egy gondosan berendezett olvasósarokban – generált enteriőr" loading="lazy" decoding="async" data-generated-interior="true"><figcaption><span>01 / A részletek számítanak</span><span>Szövet · textúra · gondoskodás</span></figcaption></figure><p class="eco-material-caption">A fotós becslés támpont. A szálösszetételt és a tisztíthatóságot a címke és a szakember vizsgálata pontosítja.</p></div>
 <div class="eco-material-workspace" data-material-app data-next="${target}"><div class="eco-material-card-heading"><span class="eco-material-eyebrow">Ismerjük meg közelebbről</span><span class="eco-material-pill">Fotóalapú anyagbecslés</span></div><h3>Egy közeli fotó segíthet.</h3><p class="eco-material-lead">Fotózd a kárpitot 10–20 cm-ről, természetes fényben, vagy válaszd a bútor kezelési címkéjét.</p>
 <div class="eco-material-drop" data-material-drop><div data-upload-prompt><span class="eco-material-focus" aria-hidden="true"><span></span></span><p><strong>Válassz egy közeli fotót.</strong><br>Húzd ide a képet, vagy válassz a fotóid közül.</p></div><div class="eco-material-preview" hidden><img alt="Az elemzésre kiválasztott saját fotód"><button type="button" data-material-clear aria-label="Kiválasztott fotó eltávolítása">×</button><span data-file-label></span></div><div class="eco-material-pickers"><button type="button" class="eco-material-button" data-material-pick>Fotó kiválasztása <span aria-hidden="true">→</span></button><button type="button" class="eco-material-button eco-material-button-quiet" data-material-camera>Fényképezés</button></div><span class="eco-material-formats">JPG, PNG vagy WebP · legfeljebb 20 MB</span><input type="file" accept="image/jpeg,image/png,image/webp" data-material-file hidden><input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" data-material-capture hidden></div>
 <label class="eco-material-note" for="material-note">Amit még érdemes tudnunk <span>nem kötelező</span><textarea id="material-note" rows="2" maxlength="1000" placeholder="Például: világos kanapé, sötétebb karfa, a címke az ülőlap alatt…"></textarea></label>
 <label class="eco-material-archive"><input type="checkbox" data-material-archive-consent disabled><span>Hozzájárulok, hogy az ECO Clean az előkészített fotót saját, privát anyagreferencia-gyűjteményében megőrizze, szakember kézzel ellenőrizze és besorolja, majd jóváhagyás után összehasonlítási mintaként későbbi elemzésekhez külső képfeldolgozó szolgáltatásnak is átadhassa.<small>Nem kötelező: a fotó megőrzése nélkül is kérhetsz elemzést. A fotó nem kerül nyilvános közzétételre.</small></span></label><p class="eco-material-archive-status" data-material-collection-status>Az anyagreferencia-gyűjtemény elérhetőségét ellenőrizzük.</p>
 <div class="eco-material-security" data-material-turnstile hidden></div>
 <div class="eco-material-submit-row"><button type="button" class="eco-material-button eco-material-analyze" data-material-analyze disabled>Elemzés indítása <span aria-hidden="true">→</span></button><button type="button" class="eco-material-example" data-material-example>Megnézek egy mintaeredményt</button></div><p class="eco-material-status" role="status" aria-live="polite" data-material-status>Válassz egy fotót a kezdéshez.</p><button type="button" class="eco-material-retry" data-material-retry hidden>Újra ellenőrzöm az elérhetőséget</button>
 <details class="eco-material-privacy"><summary>Mi történik a feltöltött képpel?</summary><p>A kép kiválasztásakor csak helyi előnézet készül. Az „Elemzés indítása” gombbal a kicsinyített fotót és megjegyzést az ECO Clean kiszolgálóján keresztül külső képfeldolgozó szolgáltatáshoz küldöd, fotóalapú anyagbecsléshez. Ha külön hozzájárulsz, az ECO Clean az előkészített JPEG-fotót privát felhőtárhelyen is megőrzi, és saját számítógépére szinkronizálhatja, kézi szakmai ellenőrzéshez és besoroláshoz. Szakmai jóváhagyás után a fotót későbbi elemzéseknél összehasonlítási mintaként külső képfeldolgozó szolgáltatásnak is átadhatja. Hozzájárulás nélkül nem kerül fotó a referenciagyűjteménybe. A fotókat nem tesszük nyilvánosan közzé. A fotón lehetőleg csak a szövet vagy a kezelési címke szerepeljen.</p></details>
 <noscript><p>Az anyagfelismerőhöz JavaScript szükséges. A bútor anyagáról telefonon is egyeztethetsz: <a href="tel:+36702408141">06 70 240 8141</a>.</p></noscript></div>
 <div class="eco-material-result" data-material-result hidden tabindex="-1" aria-label="Az anyagkalauz eredménye"></div></div>`;
 const anchor=home?d.querySelector('#booking'):d.querySelector('.studio-materials')||d.querySelector('.med-care');
 if(anchor){home?anchor.before(section):anchor.after(section);}else d.querySelector('footer')?.before(section);
 for(const [tag,url] of [['link','material-recognition/design.css'],['script','material-recognition/app.js']]){
  if(d.querySelector(`${tag}[${tag==='link'?'href':'src'}="${url}"]`))continue;
  const el=d.createElement(tag);if(tag==='link'){el.rel='stylesheet';el.href=url;d.head.append(el);}else{el.src=url;el.defer=true;d.body.append(el);}
 }
 const chapters=d.querySelector('.studio-chapters');if(chapters&&!chapters.querySelector('a[href="#anyagfelismero"]'))chapters.insertAdjacentHTML('beforeend','<a href="#anyagfelismero">Anyagfelismerő</a>');
 return section;
}
