import fs from 'node:fs';
import crypto from 'node:crypto';
const asset='material-recognition/assets/fotel-bukle-olvasosarok.webp';
export const materialAssetUrls=Object.fromEntries(['design.css','app.js'].map(file=>[file,'material-recognition/'+file+'?v='+crypto.createHash('sha256').update(fs.readFileSync(new URL(file,import.meta.url))).digest('hex').slice(0,12)]));
export function novaLifeCTA({compact=false}={}){
 return `<aside class="eco-novalife-cta${compact?' eco-novalife-cta-compact':''}" aria-label="NovaLife kárpitkalauz"><div class="eco-novalife-cta-art" aria-hidden="true"><svg width="62" height="62" viewBox="0 0 100 100" fill="none" focusable="false"><rect x="13" y="17" width="59" height="62" rx="13" stroke="currentColor" stroke-width="1.2"/><path d="M24 29c9-7 16 7 25 0s12-1 13 0M24 40c9-7 16 7 25 0s12-1 13 0M24 51c9-7 16 7 25 0M24 62c9-7 16 7 25 0M31 24v47M43 24v47M55 24v20" stroke="currentColor" stroke-width="1" opacity=".45"/><circle cx="65" cy="62" r="17" fill="#f6f2e8" stroke="currentColor" stroke-width="1.5"/><path d="m78 75 12 12M58 58c5-4 9 4 14 0M58 65c5-4 9 4 14 0M63 52v20M69 52v20" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"/><circle cx="82" cy="24" r="3" fill="#b38c77" stroke="none"/></svg></div><div class="eco-novalife-cta-copy"><span class="eco-novalife-cta-kicker">A részletek számítanak</span><h3>Bizonytalan, hogy NovaLife a kárpit?</h3><p>Egy közeli fotó segíthet felismerni a NovaLife-ra utaló jeleket. A nálunk alkalmazott tisztítás alkalmasságát a címke és a szakmai egyeztetés alapján pontosítjuk.</p></div><a href="#anyagfelismero" class="eco-novalife-cta-link">Megnézetem a szövetet <span aria-hidden="true"><svg viewBox="0 0 24 24" width="18" height="18" fill="none" focusable="false"><path d="m6 18 12-12M6 6h12v12" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></span></a></aside>`;
}
export function integrateMaterialRecognition(d,{home=false,next,assetUrl=asset}={}){
 d.getElementById('anyagfelismero')?.remove();
 d.querySelectorAll('.eco-novalife-cta').forEach(node=>node.remove());
 const target=next||(home?'#booking':d.querySelector('[data-studio-configurator]')?'#studio-kalkulator':'#arak');
 const section=d.createElement('section');section.id='anyagfelismero';section.className='eco-material';section.setAttribute('aria-labelledby','material-title');
 section.innerHTML=`<div class="eco-material-shell"><div class="eco-material-intro"><span class="eco-material-eyebrow">NovaLife vagy más kárpit? Nézzük meg közelebbről.</span><h2 id="material-title">Nem vagy biztos benne,<br>hogy NovaLife<br><em>a kárpit?</em></h2><p>Mutass egy közeli fotót, és megpróbáljuk felismerni a NovaLife-ra vagy hasonló bevonatra utaló jeleket, miközben az anyag jellegéről is támpontot adunk. Ha a képből nem dönthető el, a kezelési címke vagy egy újabb részletfotó segíthet.</p><figure class="eco-material-editorial"><img src="${assetUrl}" width="1448" height="1086" alt="Világos bukléfotel egy gondosan berendezett olvasósarokban – generált enteriőr" loading="lazy" decoding="async" data-generated-interior="true"><figcaption><span>01 / A részletek számítanak</span><span>Szövet · textúra · gondoskodás</span></figcaption></figure><p class="eco-material-caption">A fotó előzetes kockázatszűréshez ad támpontot. A NovaLife hiányát, a szálösszetételt és a tisztíthatóságot önmagában nem igazolja.</p></div>
 <div class="eco-material-workspace" data-material-app data-next="${target}"><div class="eco-material-card-heading"><span class="eco-material-eyebrow">Kezdjük a szövet részleteivel</span><span class="eco-material-pill">NovaLife-kockázatszűrés</span></div><h3>Egy közeli fotó segíthet.</h3><p class="eco-material-lead">Fotózd a kárpitot 10–20 cm-ről, természetes fényben, vagy válaszd a bútor kezelési címkéjét.</p>
 <div class="eco-material-drop" data-material-drop><div data-upload-prompt><span class="eco-material-focus" aria-hidden="true"><span></span></span><p><strong>Válassz egy közeli fotót.</strong><br>Húzd ide a képet, vagy válassz a fotóid közül.</p></div><div class="eco-material-preview" hidden><img alt="Az elemzésre kiválasztott saját fotód"><button type="button" data-material-clear aria-label="Kiválasztott fotó eltávolítása">×</button><span data-file-label></span></div><div class="eco-material-pickers"><button type="button" class="eco-material-button" data-material-pick>Fotó kiválasztása <span aria-hidden="true">→</span></button><button type="button" class="eco-material-button eco-material-button-quiet" data-material-camera>Fényképezés</button></div><span class="eco-material-formats">JPG, PNG vagy WebP · legfeljebb 20 MB</span><input type="file" accept="image/jpeg,image/png,image/webp" data-material-file hidden><input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" data-material-capture hidden></div>
 <label class="eco-material-note" for="material-note">Amit még érdemes tudnunk <span>nem kötelező</span><textarea id="material-note" rows="2" maxlength="1000" placeholder="Például: világos kanapé, sötétebb karfa, a címke az ülőlap alatt…"></textarea></label>
 <label class="eco-material-archive"><input type="checkbox" data-material-archive-consent disabled><span>Hozzájárulok, hogy az ECO Clean az előkészített fotót saját, privát anyagreferencia-gyűjteményében megőrizze, szakember kézzel ellenőrizze és besorolja, majd jóváhagyás után összehasonlítási mintaként későbbi elemzésekhez külső képfeldolgozó szolgáltatásnak is átadhassa.<small>Nem kötelező: a fotó megőrzése nélkül is kérhetsz elemzést. A fotó nem kerül nyilvános közzétételre.</small></span></label><p class="eco-material-archive-status" data-material-collection-status>Az anyagreferencia-gyűjtemény elérhetőségét ellenőrizzük.</p>
 <div class="eco-material-security" data-material-turnstile hidden></div>
 <div class="eco-material-submit-row"><button type="button" class="eco-material-button eco-material-analyze" data-material-analyze disabled>Elemzés indítása <span aria-hidden="true">→</span></button><button type="button" class="eco-material-example" data-material-example>Megnézek egy mintaeredményt</button></div><p class="eco-material-status" role="status" aria-live="polite" data-material-status>Válassz egy fotót a kezdéshez.</p><button type="button" class="eco-material-retry" data-material-retry hidden>Újra ellenőrzöm az elérhetőséget</button>
 <details class="eco-material-privacy"><summary>Mi történik a feltöltött képpel?</summary><p>A kép kiválasztásakor csak helyi előnézet készül. Az „Elemzés indítása” gombbal a kicsinyített fotót és megjegyzést az ECO Clean kiszolgálóján keresztül külső képfeldolgozó szolgáltatáshoz küldöd, fotóalapú anyagbecsléshez. Ha külön hozzájárulsz, az ECO Clean az előkészített JPEG-fotót privát felhőtárhelyen is megőrzi, és saját számítógépére szinkronizálhatja, kézi szakmai ellenőrzéshez és besoroláshoz. Szakmai jóváhagyás után a fotót későbbi elemzéseknél összehasonlítási mintaként külső képfeldolgozó szolgáltatásnak is átadhatja. Hozzájárulás nélkül nem kerül fotó a referenciagyűjteménybe. A fotókat nem tesszük nyilvánosan közzé. A fotón lehetőleg csak a szövet vagy a kezelési címke szerepeljen.</p></details>
 <noscript><p>Az anyagfelismerőhöz JavaScript szükséges. A bútor anyagáról telefonon is egyeztethetsz: <a href="tel:+36702408141">06 70 240 8141</a>.</p></noscript></div>
 <div class="eco-material-result" data-material-result hidden tabindex="-1" aria-label="Az anyagkalauz eredménye"></div></div>`;
 const medConfig=d.querySelector('[data-med-configurator]'),studioConfig=d.querySelector('[data-studio-configurator]'),warning=d.querySelector('.pricing-note-box');
 if(home){const step=d.querySelector('#priceConfigurator #step2');if(step)step.insertAdjacentHTML('afterend',novaLifeCTA({compact:true}));}
 else if(medConfig)medConfig.insertAdjacentHTML('beforebegin',novaLifeCTA());
 else if(studioConfig)studioConfig.insertAdjacentHTML('beforebegin',novaLifeCTA());
 else if(warning)warning.insertAdjacentHTML('beforeend',novaLifeCTA({compact:true}));
 const prices=d.querySelector('#arak'),anchor=home?d.querySelector('#booking'):prices?.closest('section')||prices||studioConfig?.closest('section')||d.querySelector('.studio-materials')||d.querySelector('.med-care');
 if(anchor){home?anchor.before(section):anchor.after(section);}else d.querySelector('footer')?.before(section);
 for(const [tag,file] of [['link','design.css'],['script','app.js']]){
  const attr=tag==='link'?'href':'src',url=materialAssetUrls[file];
  const existing=d.querySelector(`${tag}[${attr}^="material-recognition/${file}"]`);
  if(existing){existing.setAttribute(attr,url);continue;}
  const el=d.createElement(tag);if(tag==='link'){el.rel='stylesheet';el.href=url;d.head.append(el);}else{el.src=url;el.defer=true;d.body.append(el);}
 }
 const chapters=d.querySelector('.studio-chapters');if(chapters&&!chapters.querySelector('a[href="#anyagfelismero"]'))chapters.insertAdjacentHTML('beforeend','<a href="#anyagfelismero">Anyagfelismerő</a>');
 return section;
}
